services:
  - type: web
    name: aiflux
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_STORAGE_BUCKET
        value: flux-files
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
